version: '3'
services:
  dbpostgres:
    image: 'postgres:12.3-alpine'
    container_name: 'havbruksloggen_db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'havbruksloggen_db'
