// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200703052047_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BL.Entities.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("B")
                        .HasColumnName("b")
                        .HasColumnType("double precision");

                    b.Property<int>("BuildNumber")
                        .HasColumnName("build_number")
                        .HasColumnType("integer");

                    b.Property<double>("LOA")
                        .HasColumnName("loa")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnName("picture")
                        .HasColumnType("text");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnName("producer")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_boats");

                    b.ToTable("boats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            B = 3.2000000000000002,
                            BuildNumber = 1,
                            LOA = 5.25,
                            Name = "Boat 1",
                            Picture = "https://i.imgur.com/bd4DnKf.jpg",
                            Producer = "Producer 2"
                        },
                        new
                        {
                            Id = 2,
                            B = 2.2000000000000002,
                            BuildNumber = 2,
                            LOA = 4.25,
                            Name = "Boat 2",
                            Picture = "https://i.imgur.com/bd4DnKf.jpg",
                            Producer = "Producer1"
                        },
                        new
                        {
                            Id = 3,
                            B = 4.2000000000000002,
                            BuildNumber = 3,
                            LOA = 6.25,
                            Name = "Boat 3",
                            Picture = "https://i.imgur.com/bd4DnKf.jpg",
                            Producer = "Producer 3"
                        },
                        new
                        {
                            Id = 4,
                            B = 2.2000000000000002,
                            BuildNumber = 4,
                            LOA = 4.25,
                            Name = "Boat 4",
                            Picture = "https://i.imgur.com/bd4DnKf.jpg",
                            Producer = "Producer 4"
                        },
                        new
                        {
                            Id = 5,
                            B = 2.2000000000000002,
                            BuildNumber = 5,
                            LOA = 4.25,
                            Name = "Boat 5",
                            Picture = "https://i.imgur.com/bd4DnKf.jpg",
                            Producer = "Producer 5"
                        });
                });

            modelBuilder.Entity("BL.Entities.CrewMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Age")
                        .HasColumnName("age")
                        .HasColumnType("integer");

                    b.Property<int>("BoatId")
                        .HasColumnName("boat_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CertifiedUntil")
                        .HasColumnName("certified_until")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnName("picture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnName("role")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_crew_members");

                    b.HasIndex("BoatId")
                        .HasName("ix_crew_members_boat_id");

                    b.ToTable("crew_members");
                });

            modelBuilder.Entity("BL.Entities.CrewMember", b =>
                {
                    b.HasOne("BL.Entities.Boat", "Boat")
                        .WithMany("Crew")
                        .HasForeignKey("BoatId")
                        .HasConstraintName("fk_crew_members_boats_boat_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
